name = "metaverse-standards-platform"
compatibility_date = "2024-08-18"
compatibility_flags = ["nodejs_compat"]

[env.development]
compatibility_date = "2024-08-18"

# D1 database binding
[[env.development.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "your-d1-database-id"

[[env.production.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-prod"
database_id = "your-d1-database-id"

# Pages configuration
[build]
command = "npm run build"
destination = ".next"

# Environment variables
[env.development.vars]
NODE_ENV = "development"
NEXTAUTH_SECRET = "your-dev-secret"
NEXTAUTH_URL = "http://localhost:3000"

[env.production.vars]
NODE_ENV = "production"