name = "metaverse-standards-platform"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 database binding for local development
[[d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

[env.development]
compatibility_date = "2024-09-23"

[[env.production.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

# Pages configuration
# Note: destination moved to Pages dashboard configuration

# Environment variables
[env.development.vars]
NODE_ENV = "development"

[env.production.vars]
NODE_ENV = "production"