name = "metaverse-standards-platform"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "MSP"
database_name = "msp"
database_id = "f50218e6-2a9f-432a-a565-1469fcc461a6"

[env.production]
name = "metaverse-standards-platform"

[env.production.d1_databases]
MSP = { database_name = "msp", database_id = "f50218e6-2a9f-432a-a565-1469fcc461a6" }

[env.development]
name = "metaverse-standards-platform-dev"

[env.development.d1_databases]
MSP = { database_name = "msp", database_id = "f50218e6-2a9f-432a-a565-1469fcc461a6" }

# 환경 변수 (production용 - 실제 배포시 Cloudflare 대시보드에서 설정)
[vars]
NODE_ENV = "production"