name = "metaverse-standards-platform"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# D1 database binding for local development
[[d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

# Preview environment (for branch deployments)
[env.preview]
compatibility_date = "2024-09-23"

[[env.preview.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

# Production environment (for main branch)
[env.production]
compatibility_date = "2024-09-23"

[[env.production.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"