name = "msp-standard-recommend-sync-consumer"
main = "standard-recommend-sync-consumer.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[kv_namespaces]]
binding = "STANDARD_SEARCH_CACHE"
id = "63990b85156e4e5eac3b2e94c49d6111"

[[d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

[[queues.consumers]]
queue = "msp-standard-recommend-sync-dev"
max_batch_size = 1

[env.preview]
compatibility_date = "2024-09-23"

[[env.preview.kv_namespaces]]
binding = "STANDARD_SEARCH_CACHE"
id = "63990b85156e4e5eac3b2e94c49d6111"

[[env.preview.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

[[env.preview.queues.consumers]]
queue = "msp-standard-recommend-sync-preview"
max_batch_size = 1

[env.production]
compatibility_date = "2024-09-23"

[[env.production.kv_namespaces]]
binding = "STANDARD_SEARCH_CACHE"
id = "63990b85156e4e5eac3b2e94c49d6111"

[[env.production.d1_databases]]
binding = "MSP"
database_name = "metaverse-standards-dev"
database_id = "5bca3ce1-0488-47bb-95ec-3d8cbb347c43"

[[env.production.queues.consumers]]
queue = "msp-standard-recommend-sync-production"
max_batch_size = 1
